const API="http://127.0.0.1:5000/api";let map,chart,history;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function api(path,opt={}){const r=await fetch(API+path,opt);if(!r.ok)throw Error(await r.text());return r.json()}

document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));$(b.dataset.p).classList.add("active");b.classList.add("active");loadPage(b.dataset.p)});
function loadPage(p){if(p==="traffic")loadTraffic();if(p==="signals")loadSignals();if(p==="incidents")loadIncidents();if(p==="analytics")loadAnalytics()}

async function health(){try{await api("/health");$("status").textContent="● Backend Online"}catch{$("status").textContent="● Backend Offline"}}
async function summary(){try{let x=await api("/traffic/summary");$("total").textContent=x.total;$("speed").textContent=Number(x.average_speed).toFixed(1)+" km/h";$("dens").textContent=Number(x.density).toFixed(1)+"%";$("level").textContent=x.congestion}catch{}}
async function loadTraffic(){try{let r=await api("/traffic/current");$("trafficRows").innerHTML=r.map(x=>`<tr><td>${esc(x.camera_name)}</td><td>${esc(x.location)}</td><td>${x.cars}</td><td>${x.bikes}</td><td>${x.buses}</td><td>${x.trucks}</td><td>${x.total}</td><td>${x.average_speed}</td><td>${x.density}%</td><td>${x.congestion}</td></tr>`).join("");draw(r)}catch{$("trafficRows").innerHTML="<tr><td colspan=10>Start the backend first.</td></tr>"}}
function draw(r){if(chart)chart.destroy();chart=new Chart($("chart"),{type:"bar",data:{labels:r.map(x=>x.camera_name),datasets:[{label:"Vehicles",data:r.map(x=>x.total)}]}})}
async function loadSignals(){try{let r=await api("/signals");$("signalRows").innerHTML=r.map(x=>`<tr><td>${x.junction}</td><td>${x.direction}</td><td>${x.green_time}s</td><td>${x.yellow_time}s</td><td>${x.red_time}s</td></tr>`).join("");$("junction").innerHTML=[...new Set(r.map(x=>x.junction))].map(x=>`<option>${x}</option>`).join("")}catch{}}
async function optimize(){let x=await api("/signals/optimize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({junction:$("junction").value})});$("signalOut").className="result";$("signalOut").innerHTML=`<p>Traffic density: <b>${x.traffic_density}%</b></p><table><tr><th>Direction</th><th>Current</th><th>AI Recommendation</th><th></th></tr>${x.recommendations.map(r=>`<tr><td>${r.direction}</td><td>${r.old_green_time}s</td><td>${r.recommended_green_time}s</td><td><button onclick="applySignal(${r.id},${r.recommended_green_time})">Apply</button></td></tr>`).join("")}</table>`}
async function applySignal(id,t){await api("/signals/apply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signal_id:id,green_time:t})});loadSignals();alert("Simulation signal timing updated.")}

$("detect").onsubmit=async e=>{e.preventDefault();let f=new FormData();f.append("image",$("image").files[0]);$("detectOut").innerHTML="Analyzing...";try{let x=await api("/detection/image",{method:"POST",body:f});$("detectOut").innerHTML=`<div class="result"><b>Mode: ${x.mode}</b><div class="metricgrid">${["cars","bikes","buses","trucks"].map(k=>`<div class="metric">${k}<b>${x[k]}</b></div>`).join("")}</div><p>Total: <b>${x.total}</b> · Density: <b>${x.density}%</b> · Congestion: <b>${x.congestion}</b></p></div>`}catch(err){$("detectOut").textContent=err.message}}
$("incident").onsubmit=async e=>{e.preventDefault();await api("/incidents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({location:$("loc").value,type:$("type").value,severity:$("sev").value,confidence:$("conf").value,description:$("desc").value})});e.target.reset();loadIncidents()}
async function loadIncidents(){try{let r=await api("/incidents");$("incRows").innerHTML=r.length?r.map(x=>`<div class="result"><b>${esc(x.type)}</b> — ${esc(x.location)}<br>Severity: ${x.severity} · Confidence: ${x.confidence} · Status: ${x.status}<br>${x.status!=="RESOLVED"?`<button onclick="resolveIncident(${x.id})">Resolve</button>`:"Resolved"}</div>`).join(""):"No incidents reported."}catch{}}
async function resolveIncident(id){await api("/incidents/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"RESOLVED"})});loadIncidents()}
async function loadAnalytics(){try{let s=await api("/analytics/stats");$("records").textContent=s.records;$("vehicles").textContent=s.vehicles;$("aspeed").textContent=s.average_speed+" km/h";$("adens").textContent=s.average_density+"%";let r=await api("/analytics/overview");if(history)history.destroy();history=new Chart($("history"),{type:"line",data:{labels:r.map(x=>x.timestamp),datasets:[{label:"Vehicles",data:r.map(x=>x.total)},{label:"Density %",data:r.map(x=>x.density)}]}})}catch{}}
async function predict(){let x=await api("/prediction/forecast");$("prediction").innerHTML=`<div class="result"><b>${x.predicted_congestion}</b><br>Current average: ${x.current_average} vehicles<br>Predicted in 15 minutes: ${x.predicted_vehicles}<br>Model: ${x.model}</div>`}
$("route").onsubmit=async e=>{e.preventDefault();let s=await api("/traffic/summary");let alt=s.density>=70;$("routeOut").innerHTML=`<div class="result"><h3>${alt?"Alternative Route Recommended":"Primary Route Recommended"}</h3><p>Current network density: ${Number(s.density).toFixed(1)}%. This is a project simulation based on current traffic conditions.</p></div>`}
function initMap(){map=L.map("map").setView([12.9716,77.5946],11);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);[[12.9716,77.5946,"Junction 1"],[12.9784,77.6408,"Junction 2"],[12.9352,77.6245,"Junction 3"],[12.9569,77.7011,"Junction 4"]].forEach(x=>L.marker([x[0],x[1]]).addTo(map).bindPopup(x[2]))}
async function refreshAll(){await health();await summary();await loadTraffic();await loadSignals();await loadIncidents();await loadAnalytics()}
window.onload=()=>{initMap();refreshAll()}
